### ISSUE TITLE
[Feature Request]: graceful shutdown

### ISSUE THREAD

**Issue by afpro** [hrxi/tracing-loki#17]
i'm using tracing-loki in axum based web service, can't figure out how to make sure loki message flush to server before shutdown.

(if this is still not supported, maybe we can add shutdown method to tracing_loki::Layer. i can make a PR if this is ok.)

**Comment by afpro** [comment]
https://github.com/hrxi/tracing-loki/pull/18
i open a PR, with Layer shutdown function, and optimize Cargo.toml dependency version.

**Comment by hrxi** [comment]
Fixed by #18.
