### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tazz4843** [hrxi/tracing-loki#23]
Noticed that the crate states it's licensed under MIT/Apache 2.0 but there's no reference to that in the repo itself, would be best to add a LICENSE file to ensure there's no confusion. Thanks for the crate!

**Comment by hrxi** [comment]
There's a reference to it in the repo, in each of the Cargo.tomls. Would you prefer me adding the license texts as well?

**Comment by tazz4843** [comment]
That would be preferable, yes.
