### ISSUE TITLE
Potential bug in reserved label name

### ISSUE THREAD

**Issue by Veetaha** [hrxi/tracing-loki#6]
Reading the source code, I suppose this line is wrong. Shouldn't it check for `"level"` label name instead?

https://github.com/hrxi/tracing-loki/blob/07fac0da5d270d10cbc4c82e4ff36cdd999e9718/src/lib.rs#L397-L399

**Comment by hrxi** [comment]
Your assessment looks correct.

**Comment by lodenrogue** [comment]
Is it as simple as replacing "label" with "level"? If so I can do that.

**Comment by lodenrogue** [comment]
PR: https://github.com/hrxi/tracing-loki/pull/7

**Comment by hrxi** [comment]
Fixed by #7.

**Comment by hrxi** [comment]
Are you affected by this issue and need a new minor version?

**Comment by Veetaha** [comment]
Me personally not 😉
